### ISSUE TITLE
Update to new ClickUp API

### ISSUE THREAD

**Issue by eclipse313** [howyi/clickup-php#6]
Hello,

a lot has happened at ClickUp since the last commit in 2018. There are comments, tags to tasks, a new time tracking and much more. 

There is also a new major version 2 of the API: https://clickup.com/api

Are there any plans to update this repository to the new features?

Thanks a lot

**Comment by baticag** [comment]
This would be great to see, especially because of DELETE task function, which cannot be done without v2 API.
